name: Test Action (PHP)

on:
  push:
    paths:
      - ".github/workflows/test-action-php.yml"
      - "action.yml"
      - "Dockerfile"
      - "entrypoint.py"
      - "pyproject.toml"

  pull_request:
    branches:
      - "master"
    paths:
      - ".github/workflows/test-action-php.yml"
      - "action.yml"
      - "Dockerfile"
      - "entrypoint.py"
      - "pyproject.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  test-output-method-setup:
    name: Min Version 7.3
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Get Versions
        uses: ./
        id: get-versions
        with:
          language: php
          min-version: "7.3"

  test-output-method-load:
    name: Min Version 7.3
    needs:
      - test-output-method-setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.test-output-method-setup.outputs.version-matrix) }}
    steps:
      - name: Set Up PHP ${{ matrix.version }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # v2.37.2
        with:
          php-version: ${{ matrix.version }}

  test-output-method-setup-eol:
    name: Min Version EOL
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Get Versions
        uses: ./
        id: get-versions
        with:
          language: php

  test-output-method-load-eol:
    name: Min Version EOL
    needs:
      - test-output-method-setup-eol
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.test-output-method-setup-eol.outputs.version-matrix) }}
    steps:
      - name: Set Up PHP ${{ matrix.version }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # v2.37.2
        with:
          php-version: ${{ matrix.version }}

  test-output-method-setup-highest-only:
    name: Highest Version Only
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Get Versions
        uses: ./
        id: get-versions
        with:
          language: php
          highest-only: true

  test-output-method-load-highest-only:
    name: Highest Version Only
    needs:
      - test-output-method-setup-highest-only
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # v2.37.2
        with:
          php-version: ${{ needs.test-output-method-setup-highest-only.outputs.highest-version }}

  test-output-method-setup-highest-only-strip-patch:
    name: Highest Version Only (Strip Patch)
    runs-on: ubuntu-latest
    outputs:
      highest-version: ${{ steps.get-versions.outputs.latest-versions }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Get Versions
        uses: ./
        id: get-versions
        with:
          language: php
          highest-only: true
          remove-patch-version: true

  test-output-method-load-highest-only-strip-patch:
    name: Highest Version Only (Strip Patch)
    needs:
      - test-output-method-setup-highest-only-strip-patch
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP ${{ needs.test-output-method-setup-highest-only-strip-patch.outputs.highest-version }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240  # v2.37.2
        with:
          php-version: ${{ needs.test-output-method-setup-highest-only-strip-patch.outputs.highest-version }}

  generate-workflow-summary:
    name: Generate Workflow Summary
    needs:
      - test-output-method-load
      - test-output-method-load-eol
      - test-output-method-load-highest-only
      - test-output-method-load-highest-only-strip-patch
    if: always()
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-workflow-summary.yml@master

  generate-workflow-notifications:
    name: Generate Workflow Notifications
    needs:
      - generate-workflow-summary
    if: always()
    uses: the-lupaxa-project/workflows/.github/workflows/reusable-workflow-notifier.yml@master
    with:
      notify_on_results: "failure,timed_out"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
